# Generated by Django 4.2.6 on 2023-10-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('documento', models.IntegerField(verbose_name='')),
                ('telefono', models.IntegerField(verbose_name='')),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tareas',
            name='completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
