# Generated by Django 4.2.6 on 2023-10-30 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cliente_alter_tareas_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{9,12}$')]),
        ),
    ]
