# Generated by Django 4.2.6 on 2023-10-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cliente_correo_alter_cliente_documento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
