# Generated by Django 4.2.6 on 2023-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_cliente_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='tareas',
            name='trabajoarealizar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='trabajosolicitado',
            field=models.TextField(blank=True),
        ),
    ]
