# Generated by Django 4.2.6 on 2023-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_tareas_importante_remove_tareas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(default='00000000', max_length=10),
        ),
    ]
