# Generated by Django 4.2.6 on 2023-10-30 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_cliente_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}-[0-9]+$')]),
        ),
    ]
