# Generated by Django 4.2.6 on 2023-10-30 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_cliente_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9-]+$')]),
        ),
    ]
