# Generated by Django 4.2.6 on 2023-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha',
            field=models.TextField(blank=True),
        ),
    ]
