# Generated by Django 4.2.6 on 2023-11-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_tareas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='fecha',
        ),
    ]
