# Generated by Django 4.2.6 on 2023-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_tareas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='tareas',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
