# Generated by Django 4.2.6 on 2024-01-13 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_tareas_nombre_tareas_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('nombre', models.TextField()),
                ('especificacion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
            ],
        ),
        migrations.AlterField(
            model_name='tareas',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
